import { describe, expect, it } from 'vitest';
import { createVitest, DefaultReporter, TestCase, TestSuite, TestModule, type SerializedError, type TestRunResult } from 'vitest/node';
import { join, relative } from 'node:path';
import { cp, mkdir, readFile, rm } from 'node:fs/promises';
import bundleWasm from '@/vite.js';

const fixturesDir = join(import.meta.dirname, './fixtures');

describe('bundleWasm Vite plugin', () => {
  it('should load wasm-binary bytes from a runtime dynamic import in Vitest SSR', async (): Promise<void> => {
    /// @case
    /// 1. A Vitest user configures bundleWasm({ test: true }) through its public Vite plugin entry.
    /// 2. A test module dynamically imports a local ".wasm?wasm-binary" file at runtime.
    /// @expect
    /// The dynamic import resolves to wasm bytes without leaking an internal virtual id to Node native ESM import.
    const result = await runTestFixture(fixtureOf`dynamic-wasm-binary`, {
      inlineDependencies: true,
    });
    expect(result.ok, formatErrors(result.errors)).toBe(true);
  });

  it('should load wasm-binary bytes from a published dependency in Vitest SSR', async (): Promise<void> => {
    /// @case
    /// 1. A Vitest user configures bundleWasm({ test: true }) through its public Vite plugin entry.
    /// 2. A dependency package exports JavaScript from its built output folder.
    /// 3. The dependency JavaScript dynamically imports "./fixture.wasm?wasm-binary" at runtime.
    /// @expect
    /// Static imports generated by the plugin do not leak internal virtual ids to Node native ESM import.
    const result = await runTestFixture(fixtureOf`published-dynamic-wasm-binary`, {
      inlineDependencies: [
        /\/published-wasm-binary-consumer\/.*\.[cm]?[jt]s/,
      ],
    });
    expect(result.ok, formatErrors(result.errors)).toBe(true);
  });
});

function fixtureOf(name: TemplateStringsArray): string {
  return join(fixturesDir, name.join(''));
}

async function runTestFixture(fixtureDir: string, opts: FixtureRunOptions): Promise<FixtureRunResult> {
  await installFixtureDependencies(fixtureDir);

  const reporter = new FixtureReporter(relative(fixturesDir, fixtureDir), {});
  const vitest = await createVitest(
    'test',
    {
      root: fixtureDir,
      passWithNoTests: false,
      watch: false,
      run: true,
      config: false,
      reporters: [
        reporter,
      ],
      projects: [{
        root: fixtureDir,
        test: {
          environment: 'node',
          fileParallelism: false,
          maxWorkers: 1,
          server: opts.inlineDependencies
            ? {
              deps: {
                inline: opts.inlineDependencies,
              },
            }
            : undefined,
        },
        plugins: [
          bundleWasm({
            test: true,
          }),
        ],
        resolve: {
          alias: [
            {
              find: 'cc/env',
              replacement: join(fixtureDir, 'cc-env.ts'),
            },
          ],
        },
      }],
    },
  );
  try {
    const result = await vitest.start();
    return new FixtureRunResult(result);
  } finally {
    await vitest.close();
  }
}

interface FixtureRunOptions {
  inlineDependencies: boolean | (string | RegExp)[];
}

async function installFixtureDependencies(fixtureDir: string): Promise<void> {
  const nodeModulesDir = join(fixtureDir, 'node_modules');
  const dependencySourceDir = join(fixtureDir, 'dependency');
  const dependencyPackageJson = JSON.parse(await readFile(join(dependencySourceDir, 'package.json'), 'utf8')) as DependencyPackageJson;
  if (!dependencyPackageJson.name) {
    throw new Error(`Missing fixture dependency package name: ${dependencySourceDir}`);
  }
  const dependencyTargetDir = join(nodeModulesDir, dependencyPackageJson.name);

  await rm(dependencyTargetDir, {
    force: true,
    recursive: true,
  });
  await mkdir(nodeModulesDir, {
    recursive: true,
  });
  await cp(dependencySourceDir, dependencyTargetDir, {
    recursive: true,
  });
}

interface DependencyPackageJson {
  name?: string;
}

class FixtureReporter extends DefaultReporter {
  constructor(private _fixtureName: string, options: ConstructorParameters<typeof DefaultReporter>[0]) {
    super(options);
  }

  override log(...messages: unknown[]): void {
    super.log(...this._prefixMessages(messages));
  }

  override error(...messages: unknown[]): void {
    super.error(...this._prefixMessages(messages));
  }

  private _prefixMessages(messages: unknown[]): unknown[] {
    if (messages.length === 0) {
      return messages;
    }
    if (typeof messages[0] === 'string') {
      return messages.map((m) => `[${this._fixtureName}] ${m}`);
    }
    return [`[${this._fixtureName}]`, ...messages];
  }
}

class FixtureRunResult {
  constructor(private _result: TestRunResult) {
    if (this._result.unhandledErrors.length > 0) {
      this._ok = false;
      this._errors.push(...this._result.unhandledErrors.map(toSerializedError));
    }
    for (const test of this._result.testModules) {
      if (test.state() !== 'passed') {
        this._ok = false;
      }
      this._collectErrorsInTestModule(test);
    }
    if (this._errors.length > 0) {
      this._ok = false;
    }
  }

  get ok(): boolean {
    return this._ok;
  }

  get errors(): SerializedError[] {
    return this._errors;
  }

  private _ok = true;
  private _errors: SerializedError[] = [];

  private _collectErrorsInTestModule(testModule: TestModule): void {
    this._errors.push(...testModule.errors());
    for (const test of testModule.children) {
      this._collectErrorsInTestChild(test);
    }
  }

  private _collectErrorsInTestChild(testChild: TestSuite | TestCase): void {
    if (testChild.type === 'suite') {
      this._collectErrorsInTestSuite(testChild);
      for (const test of testChild.children) {
        this._collectErrorsInTestChild(test);
      }
    } else {
      this._collectErrorsInTestCase(testChild);
    }
  }

  private _collectErrorsInTestSuite(testSuite: TestSuite): void {
    this._errors.push(...testSuite.errors());
  }

  private _collectErrorsInTestCase(testCase: TestCase): void {
    this._errors.push(...(testCase.result().errors || []));
  }
}

function toSerializedError(error: unknown): SerializedError {
  if (error instanceof Error) {
    return {
      message: error.message,
      stack: error.stack,
    };
  }
  if (typeof error === 'object' && error !== null) {
    return error as SerializedError;
  }
  return {
    message: String(error),
  };
}

function formatErrors(errors: SerializedError[]): string {
  return errors.map((error, index) => {
    return [
      `Fixture error ${index + 1}:`,
      error.message,
      error.cause?.message ? `Cause: ${error.cause.message}` : undefined,
      error.stack,
    ].filter((line) => line !== undefined && line !== '').join('\n');
  }).join('\n\n');
}
